spring.application.name=bdget

# --- DESACTIVADO PARA PRUEBAS LOCALES MÁS RÁPIDAS ---
# spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
# spring.cloud.config.fail-fast=false
spring.cloud.config.enabled=false
spring.cloud.config.import-check.enabled=false

# --- LOGS PARA VER LA CREACIÓN DE TABLAS ---
logging.level.root=INFO
logging.level.org.hibernate=DEBUG
logging.level.org.springframework=DEBUG

# --- CONEXIÓN A BASE DE DATOS ---
spring.datasource.url=jdbc:oracle:thin:@duocuc_tp?TNS_ADMIN=/app/wallet
spring.datasource.username=ADMIN
spring.datasource.password=aa.123654789.AA
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# --- CONFIGURACIÓN JPA / HIBERNATE ---
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true
# Esto creará las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update

# --- CONFIGURACIÓN POOL CONEXIONES ---
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000

server.port=8080